---
- name: Restart webapp
  hosts: all
  become: yes

  tasks:
    - name: Restart docker-compose
      shell: |
        cd /app/inHoliday && docker stop $(docker ps -a -q) && \
        docker rm $(docker ps -a -q) && \
        doppler run --token='{{ DOPPLER_TOKEN }}' -- docker-compose up -d
